name: Publish

on:
  release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: |
          git config --global user.email "joepittsy@gmail.com"
          git config --global user.name "Joseph Pitts"
          npm version minor
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
